// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNYtUi-RDOxU__sxoT3MlVBnmE5GkB8uI',
    appId: '1:279323547618:android:98a354646200d49f6b4bbb',
    messagingSenderId: '279323547618',
    projectId: 'foam-shop-register',
    storageBucket: 'foam-shop-register.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMbLy1wnydBBK-UUuMU5jyI4Rk-HJrvw',
    appId: '1:279323547618:ios:db470720ee8cb3456b4bbb',
    messagingSenderId: '279323547618',
    projectId: 'foam-shop-register',
    storageBucket: 'foam-shop-register.firebasestorage.app',
    androidClientId: '279323547618-eqpsqq00don7uaff555j8sdf08dp67c1.apps.googleusercontent.com',
    iosClientId: '279323547618-7ihddr46jrba72mhhnps40h4n10mqoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foamShopRegister',
  );
}
